name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Install dependencies
        run: |
          cd /home/khanh/web-file-manager-server
          git pull
          pnpm install --frozen-lockfile

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy server
        run: pm2 restart 'web file'

# name: Node.js CI

# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [20.x]

#     steps:
#       - name: Pull latest code
#         run: |
#           cd /home/khanh/web-file-manager-server  # Thay đổi đường dẫn đến thư mục ứng dụng
#           git pull origin main
#       - name: Install dependencies
#         run: |
#           cd /home/khanh/web-file-manager-server
#           npm ci
#       - name: Restart PM2
#         run: pm2 restart "web file"

